knaxus/problem-solving-javascript

- src/_Problems_/merge-two-sorted-arrays/index.js
- src/_Problems_/merge-two-sorted-arrays/merge-two-sorted-arrays.test.js
Test file for merge-two-sorted-arrays
> --update : add test file for merge-two-sorted-arrays

- src/_Problems_/product-of-elements/index.js
Changes:
- Added 2nd approach which have 3 cases to solve the problem.
1. If count of zeros is 0.
2. If count of zeros is 1.
3. If count of zeros is greater than equal to 2.
> 2nd approach for product-of-elements

- src/_Problems_/find-2-nums-adding-to-n/index.js
- src/_Problems_/find-2nd-max/index.js
Changes:
- Fix in the naming of variables
- Better comments
- returning ```null``` instead of ```false```
> Minor fixes

- package-lock.json
- src/_Problems_/find-2-nums-adding-to-n/find-2-nums-adding-to-n.test.js
- src/_Problems_/find-2-nums-adding-to-n/index.js
What's Inside? 
- Add unit tests for `find-2-nums-adding-to-n`
- Fix `findTwoNumsAddingToN2()` so it only returns one pair
> Unit tests & fix for "find-2-nums-adding-to-n"

- src/_Problems_/max-consecutive-1s/index.js
- src/_Problems_/max-consecutive-1s/max-consecutive-1s.test.js
Added 10 unit tests for `findMaxConsecutive1s`
- basic tests for combinations of 1s and 0s
- strings of `"1"` are not counted as `1`
> Add unit tests for findMaxConsecutive1s

- src/_Problems_/max-product-of-3-numbers/index.js
Changes:
- Throw error if array length less than 3.
> max-product-of-3-numbers error throw

- src/_Problems_/next-greater-element/index.js
- src/_Problems_/next-greater-element/next-greater-element.test.js
- Add tests for next-greater-element problem
> Add test for next greater element

- README.md
- src/_DataStructures_/LinkedList/reverse-linked-list/index.js
- src/_DataStructures_/LinkedList/reverse-linked-list/reverse-linked-list.test.js
I added a problem named "Reverse Linked List" with its solution to LinkedList section. It basically takes a  LinkedList as parameter, then returns the same modified LinkedList but its elements are in reverse order.
> Added Reverse Linked List Problem.

- README.md
- src/_DataStructures_/Stack/balanced-parenthesis/index.js
- src/_DataStructures_/Stack/index.js
added balanced-parenthesis problem
> balanced-parenthesis

- src/_Problems_/max-product-of-3-numbers/index.js
- src/_Problems_/max-product-of-3-numbers/max-product-of-3-numbers.test.js
- Add unit tests to Max Product of 3 numbers problem
- Export function to be used by test file
Since the problem specifies the product of **exactly 3 numbers** I was about to write the following test...
```js
it("returns an error if there are less than 3 numbers", () => {
expect(() => {
maxProductof3Numbers([-10, -1]);
}).toThrowError();
});
```
But this case is not covered by the implementation. Should I implement this test scenario?
> Add unit tests to Max Product of 3 numbers problem

- README.md
- src/_DataStructures_/Stack/2-stacks-using1-array/index.js
🏖 So what's new? 
- Added **Implementation of 2 stacks using 1 array**
- Revision to PR #35 
- Cleaned up all the bullshit
- This implementation adheres to the laws of **Stack - Data Structure**
🐳
> Implementation of 2 stacks using 1 array

- src/_DataStructures_/LinkedList/loop-in-list/index.js
- src/_DataStructures_/LinkedList/loop-in-list/loop-in-list.test.js
Add unit test to loop-in-list exercise.
Also, rename loop-in-list function name from `detech` to `detect`.
> Add unit test to loop-in-list

- README.md
- src/_DataStructures_/SuffixTree/index.js
> Add Suffix Tree

- src/_DataStructures_/Trees/BST/index.js
🚁 What's inside?
- `remove(value)` which is using `delete(root, value)` at the core  in BST
- Enhancements:
- replaced `insert(root, value)` with `add(value)`
- replaced `preorder(root)` with `traversePreorder()`
- replaced `postorder(root)` with `traversePostorder()`
- replaced `inorder(root)` with `traverseInorder()`
- replaced `search(root, value)` with `searchFor(value)`
🔧  Fixes and Updates 
-  fixed delete case of Node having 2 children, thanks @TheSTL for the feedback. 
- `getMinimum()` using `findMinNode(root)`
- `getMaximum()` using `findMaxNode(root)`
🕊
> delete() & enhancements in BST

- src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
- src/_DataStructures_/Stack/postfix-expression-evaluation/postfix-expression-evaluation.test.js
The added tests verify what the function is currently able to do, coverage is 100%.
I didn't cover the case of too few number arguments (i.e '1-*') because it returns NaN and I'm not sure if this is the desired output.
> Add unit tests to postfix expression evaluation function. Resolves #34

- src/_Algorithms_/lru-cache/LRUCache.test.js
- src/_Algorithms_/lru-cache/index.js
Add unit tests for LRUCache algorithm.
> Add tests for LRUCache

- src/_DataStructures_/LinkedList/index.js
🗒 What's Inside?
- Added **tail** and **size** as properties of LL CLass
- Now it takes constant time [O(1)] for the following:
- `length()`
- `addAtEnd(element)`
Ran `npm test` which helped me fix few breakpoints. 🎉
> Enhancements on Linked lists

- src/_DataStructures_/LinkedList/index.js
- src/_DataStructures_/Queue/Queue.test.js
- src/_DataStructures_/Queue/QueueUsingArray.js
- src/_DataStructures_/Queue/index.js
- src/_DataStructures_/Queue/weave/index.js
- src/_DataStructures_/Queue/weave/weave.test.js
👻 What's Inside?
- This PR addresses issue #60
Changes
- The new Queue Implementation has **Singly Linked List** under the hood
- The API has changed and is more close to the standard Queue Data Structure
- List of methods
- `enqueue(data)`
- `dequeue()`
- `peek()`
- length()
- Fixes all the **test cases** to use the new APIs
- Updated the code of **Weave a Queue** to use new APIs
🎉
> Re-implementation of Queue

- README.md
- src/_DataStructures_/LinkedList/index.js
- src/_DataStructures_/Queue/Queue.test.js
- src/_DataStructures_/Queue/QueueUsingArray.js
- src/_DataStructures_/Queue/generate-binary-number/index.js
- src/_DataStructures_/Queue/index.js
- src/_DataStructures_/Queue/queue-using-stack/index.js
- src/_DataStructures_/Queue/reverse-first-k/index.js
- src/_DataStructures_/Queue/weave/index.js
- src/_DataStructures_/Queue/weave/weave.test.js
- src/_DataStructures_/Stack/index.js
🔗 What's Inside?
- `generateBinaryNumbers(n)`
- `reverseFirstK(queue, k)`
- Implementation of Queue using Stack
🎉
> Problems involving Queues

- src/_Searching_/JumpSearch/JumpSearch.test.js
- src/_Searching_/JumpSearch/index.js
> Add jumpSearch and Tests

- src/_DataStructures_/Trees/BinarySearchTree/bst-insertion.test.js
Added tests for BST insertion.
Post test inclusion:
executed npm run test
All tests are passing.
> Added tests for BST insertion

- src/_Searching_/TernarySearch/TernarySearch.test.js
- src/_Searching_/TernarySearch/index.js
Attempt to solve issue [#72](https://github.com/knaxus/problem-solving-javascript/issues/72)
> Add Ternary search

- src/_DataStructures_/Trees/BinarySearchTree/bst-deletion.test.js
Added test cases for BST deletion #66
> Added test cases for BST deletion #66

- README.md
- src/_DataStructures_/Trees/BinaryTree/Node.js
- src/_DataStructures_/Trees/BinaryTree/index.js
🐔 What's new?
- Binary Tree (!BST)
- Create a BT using Level Order Array
> Added Binary Tree

- src/_DataStructures_/DoublyLinkedList/index.js
- src/_DataStructures_/LinkedList/index.js
🌵 What's inside?
- Added traverse method in LL Class to return an array of elements
- Change the variable name for the array returning elements
- change display() to traverse()
> Changes in Linked Lists

- src/_PathFinder_/AStar/AStar.test.js
- src/_PathFinder_/AStar/index.js
Added tests for the A* algorithm, aligned all names with the naming convention and added errors and return value to the A* algorithm to facilitate testing.
> Added tests for the A* algorithm and cleaned up A* directories

- src/_DataStructures_/Trees/BinaryTree/check-binary-tree-subtree-another-binary-tree/index.js
Adding and exporting a function that can take two arguments as source tree and the tree that has to be matched and checks if the second tree is the subtree of the source tree.
Logic from: https://www.geeksforgeeks.org/check-if-a-binary-tree-is-subtree-of-another-binary-tree/
> Adding Check if a binary tree is subtree of another binary tree

- README.md
- src/_DataStructures_/Trees/Trie/Node.js
- src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js
- src/_DataStructures_/Trees/Trie/get-unique-words/index.js
- src/_DataStructures_/Trees/Trie/index.js
- src/_DataStructures_/Trees/Trie/total-words-in-trie/index.js
- src/_DataStructures_/Trees/Trie/unique-word-count/index.js
🔍 What's inside?
This PR contains a few problems involving Trie DataStructure.
> Trie problems

- src/_DataStructures_/Stack/postfix-expression-evaluation/index.js
- src/_DataStructures_/Stack/postfix-expression-evaluation/postfix-expression-evaluation.test.js
- Update test case for exception
> postfix-expression-evaluation #61

- src/_Classics_/knuth-morris-pratt/index.js
- src/_Classics_/knuth-morris-pratt/knuth-morris-pratt.test.js
Story: #124
Added KMP algorithm to classics folder, along with a series of unit tests to bring the file coverage up to 100%. 
Updated file to keep in line with eslint rules. 
Added comments and time complexity of the KMP pattern matching algorithm.
Added example use case in file preamble.
> KMP classic algorithm and unit tests

- src/_DataStructures_/Trees/Trie/unique-word-count/index.js
- src/_DataStructures_/Trees/Trie/unique-word-count/index.test.js
Closes #135 
Achieves 100% coverage on `Trie/unique-word-count`, follows linter rules, and I believe it covers the important test cases.
> Add unit tests for Trie/unique-word-count

- src/_DataStructures_/Trees/BinaryTree/index.js
- src/_Problems_/binary-tree-to-binary-search-tree/Node.js
- src/_Problems_/binary-tree-to-binary-search-tree/binary-tree-to-binary-search-tree.test.js
- src/_Problems_/binary-tree-to-binary-search-tree/index.js
@ashokdey @TheSTL - Raised a new PR because the last PR was raised with the wrong Author information
> Implement Binary Tree to Binary Search Tree Conversion - Solution

- src/_DataStructures_/Trees/BinaryTree/bottom-view-binary-tree/BottomViewBinaryTree.test.js
this should help with https://github.com/knaxus/problem-solving-javascript/issues/146
please let me know what you think
> add test for bottom view binary tree

- CONTRIBUTING.md
> Changed some minor typos in Contributing.md

- src/_DataStructures_/Trees/Trie/get-unique-words/get-unique-words.test.js
https://github.com/knaxus/problem-solving-javascript/issues/143
> test: add test for get-unique-words

- src/_DataStructures_/Trees/Trie/all-words-in-trie/all-words-in-trie.test.js
- src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js
Added test, see issue https://github.com/knaxus/problem-solving-javascript/issues/144
> test: add test for all-words-in-tree

- src/_DataStructures_/LinkedList/index.js
🏷 What's Inside?
- Fix for LinkedList removeAt()
> fix: linked list removeAt()

- src/_DataStructures_/Heaps/MaxHeap/MaxHeap.test.js
- src/_DataStructures_/Heaps/MinHeap/MinHeap.test.js
- src/_DataStructures_/LinkedList/LinkedList.test.js
- src/_DataStructures_/Trees/BinaryTree/bottom-view-binary-tree/BottomViewBinaryTree.test.js
- src/_DataStructures_/Trees/BinaryTree/btree-traversals.test.js
- src/_DataStructures_/Trees/Trie/Node.js
- src/_DataStructures_/Trees/Trie/all-words-in-trie/all-words-in-trie.test.js
- src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js
- src/_DataStructures_/Trees/Trie/get-unique-words/index.js
- src/_DataStructures_/Trees/Trie/search.test.js
- src/_Problems_/binary-tree-to-binary-search-tree/binary-tree-to-binary-search-tree.test.js
- src/_Problems_/next-greater-element/index.js
- src/_Problems_/next-greater-element/next-greater-element.test.js
What's inside?
Increase code coverage of following files:
- Data Structure
- Heap
- MaxHeap
- MinHeap
- LinkedList
- Tree
- BinaryTree
- Trie
- Problems
- binary-tree-to-binary-search-tree
- next-greater-element
After merging this PR code coverage of project will be 100% :100:
> Code coverage

- README.md
- TOC.md
- src/_DataStructures_/HashTable/HashEntry.js
- src/_DataStructures_/HashTable/index.js
- src/_DataStructures_/LinkedList/index.js
🌮 What's Inside?
Added the most extensively used Data Structure - **Hash Tables** (aka Hash Map)
API Details:
- set(key, value): to set the key-value pair
- get(key): to get the value(s) associated with the given key
- delete(key): remove the key and the associated values
**Note**: Passing the same key with different value, overrides the previous value
🏖
> added Hash Table

- src/_DataStructures_/Trees/SuffixTree/SuffixTree.test.js
Fixes #87
Not sure if these tests are enough. Can't think of something more. Can you take a look?
> Add unit tests for suffix tree

- TOC.md
- src/_DataStructures_/BloomFilters/index.js
- src/_DataStructures_/HashTable/index.js
- src/_DataStructures_/Set/index.js
💮 What's Inside?
- Bloom Filters
- APIs are:
- add(element)
- containts(element)
For more details: [Bloom Filters on Wikipedia](https://en.wikipedia.org/wiki/Bloom_filter)
🎉
> Bloom filters
